language: rust
rust:
- stable
- beta
- nightly
sudo: required
script:
- cargo test
- rustdoc --test README.md -L target
- cargo doc --no-deps || echo "skipping cargo doc"
after_success: |
  if [[ "$TRAVIS_RUST_VERSION" == nightly ]]; then
    RUSTFLAGS="--cfg procmacro2_semver_exempt" cargo install cargo-tarpaulin
    cargo tarpaulin --out Xml
    bash <(curl -s https://codecov.io/bash)
  fi
notifications:
  email:
    on_success: never
addons:
  apt:
    packages:
    - libcurl4-openssl-dev
    - libelf-dev
    - libdw-dev
    - cmake
    - libssl-dev
    - gcc
    - binutils-dev
    - libiberty-dev
env:
  global:
    secure: G4LVGE1uTu3tqgn09TABN8h+UVII9cQus4zFGlDvfpw8yXNfWL/AfgDZcjMYeesdzcFNjaWvbim48Ne4kD78EjdFdvADwf7mwf1hbiq9hfdqA6EbF4dkNMj16kbTPKHn5YMZE091BqLwtYJCrV2gwlfzaVKZVzioNadaNEB55x4CA3h7A1mhjooZ2iNsjxtw+X7174CMzTRNlzcLuFuKru1elR0FsY7xM650oKC4CKfqJcLj4ueg/rwbptG6MJdnKM9FGJ3NbNGVt2GO8zbzlabSMrcfn3GXYn/fCkah9r+tNK/Y8AP2gw+dg3M+4EcGoc6mI0YgtinUp4Gz99RWa5vAhlCljrGWq4kxNC/INJLmX889vlYdpXLyAkKXi1bsH9R4nrNJqOF/hxOK/xqHDl9NbTsUJQpzMfXYHjPVWbtTAMKDv22FdsWsgLYYurDMikHvjSzpkUY++y2L79Rd7llSQ80cHrayTr1U6/lrTIOhxHXaFe3EPBgNUgAJxsbCUVbsSdTc1LnLZzylaZlmi/7DznEjZldo+rCiPZOyOQ6RgLHbBK2yVnURsjZxxxWMEELn+Cti55Hw3DRbhlsn5b4UQdsAncZnCVgkYVQqVQN0V0Znw6BF2jriAsRYhKRFd1yJBw83wQjOD/WQsMuoRn4lT+y2fs0C6j8oJRTeGkY=
