language: rust
rust:
- stable
- beta
- nightly
sudo: required
script:
- cargo test
- rustdoc --test README.md -L target
- cargo doc --no-deps || echo "skipping cargo doc"
after_success: |
  if [[ "$TRAVIS_RUST_VERSION" == nightly ]]; then
    RUSTFLAGS="--cfg procmacro2_semver_exempt" cargo install cargo-tarpaulin
    cargo tarpaulin --out Xml
    bash <(curl -s https://codecov.io/bash)
  fi
notifications:
  email:
    on_success: never
addons:
  apt:
    packages:
    - libcurl4-openssl-dev
    - libelf-dev
    - libdw-dev
    - cmake
    - libssl-dev
    - gcc
    - binutils-dev
    - libiberty-dev
env:
  global:
    secure: ks30EsPFY3RT+/hB07wCDQlJdkfm6NDbbvf5wf89QQ+yt0FnS2soZSRMGnbP/RwUWwdehQ3C0jMgRwt4Y8NGnlpm+hJDpbnA/s3o91YYEiGemKvn/TCXIZZSUUWZDIo6RFhlfYyTD9WPGPcwIKY9ZwDC6U90u/WaxBHim06+B9EJgDNcAf7FA/Xng0FDXKmB9kog2IGksLMiCSFKZrDO0IdChT1quf71T2ecPLlGHx6YWRSLFmbvU1ebXTt/luo/Vfv3H4coezerkcBNjKYNbEPrjFYrh6GxkSxGW7ih0Hrq7dZ63Ls1ah4ca1f0h1Hexx+rdbJAMCHEcwB4JuikyyBwRU/NtRCOoj4Zp0ydnA+ersxpqV7t/iBQ6HEDyTJ069HfaiEi4hm8ptY/W1/O7xvskw7ISZgfX/4R52DvLCl6npnmGxWHlWE6Jyvh+BSSOugBF27tPsLOG9lJx49fNvPmUNWkX6+zATPo0O9nxcxOf32T0bm041PUJrIZDqAg94Sonv0cmw8pj+lQMr31FWm0qNyCmUwgQQ/BYZ+30sgMmqg6PRWviJqEzMG0pVdaMeCt9JCsHfWP8aOjfcFLD6JmeNyTlQhBLfrpLCgo5YOTVs0XuvZo4C/r/mUGwwnWcZQucHMDkgWbrGWvjKseNubRAY/mIXbSwk6ReCgNBFU=
