language: rust
rust:
- stable
- beta
- nightly
sudo: required
script:
- cargo test
- rustdoc --test README.md -L target
- cargo doc --no-deps || echo "skipping cargo doc"
after_success: |
  if [[ "$TRAVIS_RUST_VERSION" == stable ]]; then
    RUSTFLAGS="--cfg procmacro2_semver_exempt" cargo install cargo-tarpaulin
    cargo tarpaulin --out Xml
    bash <(curl -s https://codecov.io/bash)
  fi
notifications:
  email:
    on_success: never
addons:
  apt:
    packages:
    - libcurl4-openssl-dev
    - libelf-dev
    - libdw-dev
    - cmake
    - libssl-dev
    - gcc
    - binutils-dev
    - libiberty-dev
env:
  global:
    secure: gxqjVqYAGxpa3qfTx/3+Enb7VloTH45xzeBvjPwuF6b8EeMOJqs4ZUPEKQU+q/x2HS+0iQXPEpZU/Pbm62C1FgzCgoZkgcbduwdyfvTS4jNqjwkyOKQ35MEIMpxLBZlwbcFZyKUTJzwWlSgYUvMWjf8HkUCsEKlwRxHCbvHKv97ekhkW4FJcu/vp4cHbRwbFn1fTybna6BGyvuJbgFlGiECIlbxU95XKMCNRlDifNNLM6d2jftz0tBPSXy17Y0+0TRuBmMP+/F5lJPhAvGpqSHOhgDxuCpbYp12Rinyj0pn2RLeZcBez+kU8VuGIEeufqcvDLiAYqgrm/QvXCBqwyLlsbhBI6pU4lBnVbpX7D61L005rjr2Z/khG9VNYTTNNS6AOYzo1ZBQwLd/v0l0zrN32qWnytfUQHX/misvdd4Ls9D4a2ekEJ4K4plho4tNxNKDUG8m7ivWhlAwGKgl6YE5++5dFV28zOLEG4Hi92WSnLwRvwK19UJ3Xzg/+Ubvr0Q9dRfJxruQkwxO7Z6IbxDSEiq3pCMPFm12al6kxnn2+d5KlZoQSF4Agk3Rh6HMWzghXh7IkYxf0jTGeJ0/y2COXid34NwxIy8MDF72UfH6/gFkpVHiRxRvbSXkmbLS07fEdhICb7EvFf4n73mJGc15JEKXHa86jJ3c8hUapDvE=
