[package]
name = "hocon"
version = "0.1.0"
authors = ["zolkko <zolkko@gmail.com>"]
edition = "2018"

[dependencies]
pest = "2.1.0"
pest_derive = "2.1.0"
serde = { version = "1.0" }

[dev-dependencies]
serde_derive = { version = "1.0" }
